name: Docker CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Build vote service
      run: docker build ./vote

    - name: Build result service
      run: docker build ./result

    - name: Build worker service
      run: docker build ./worker
